TestWebApplication/Models/ErrorViewModel.cs
namespace TestWebApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TestWebApplication/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TestWebApplication.Models
{
    public class LoginViewModel
	{
		[Required]
		[Display(Name = "Логин")]
		public string UserName { get; set; }

		[Required]
		[UIHint("password")]
		[Display(Name = "Password")]
		public string Password { get; set; }

		[Display(Name = "Запомнить")]
		public bool RememberMe { get; set; }
	}
}

TestWebApplication/Areas/Admin/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using TestWebApplication.Domain;

namespace TestWebApplication.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminController(DataManager dataManager) : Controller
	{
		private readonly DataManager dataManager = dataManager;

		public IActionResult Index() => View(dataManager.ServiceItems.Get());
	}
}

TestWebApplication/Areas/Admin/Controllers/ServiceItemsController.cs
using Microsoft.AspNetCore.Mvc;
using TestWebApplication.Domain;
using TestWebApplication.Domain.Entities;

namespace TestWebApplication.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServiceItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostEnvironment;

        public ServiceItemsController(DataManager dataManager, IWebHostEnvironment hostEnvironment)
        {
            this.dataManager = dataManager;
            this.hostEnvironment = hostEnvironment;
        }
        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new ServiceItem()
                                       : dataManager.ServiceItems.GetById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(ServiceItem model, IFormFile titleImageFile) 
        { 
            if(ModelState.IsValid)
            {
                if(titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostEnvironment.WebRootPath, "img/", titleImageFile.FileName), FileMode.Create))
                        titleImageFile.CopyTo(stream);
                }
                dataManager.ServiceItems.Save(model);
                return RedirectToAction(nameof(AdminController.Index), nameof(AdminController).Replace("Controller", string.Empty));
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.ServiceItems.Delete(id);
            return RedirectToAction(nameof(AdminController.Index), nameof(AdminController).Replace("Controller", string.Empty));
        }
    }
}

TestWebApplication/Areas/Admin/Controllers/TextFieldsController.cs
using Microsoft.AspNetCore.Mvc;
using TestWebApplication.Domain;
using TestWebApplication.Domain.Entities;

namespace TestWebApplication.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TextFieldsController : Controller
    {
        private readonly DataManager dataManager;
        public TextFieldsController(DataManager dataManager) =>
            this.dataManager = dataManager;
        public IActionResult Edit(string codeWord) =>
            View(dataManager.TextFields
                            .GetByCodeWord(codeWord));

        [HttpPost]
        public IActionResult Edit(TextField model)
        {
            if(ModelState.IsValid)
            {
                dataManager.TextFields.Save(model);
                return RedirectToAction(nameof(AdminController.Index), nameof(AdminController).Replace("Controller", string.Empty));
            }
            return View(model);
        }
    }
}

TestWebApplication/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TestWebApplication.Models;

namespace TestWebApplication.Controllers
{
	[Authorize]
	public class AccountController(UserManager<IdentityUser> userManager, 
								   SignInManager<IdentityUser> signInManager) 
		: Controller
	{
		private readonly UserManager<IdentityUser> userManager = userManager;
		private readonly SignInManager<IdentityUser> signInManager = signInManager;

		[AllowAnonymous]
		public IActionResult Login(string returnUrl)
		{
			ViewBag.returnUrl = returnUrl;
			return View(new LoginViewModel());
		}
		[HttpPost]
		[AllowAnonymous]
		public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
		{
			if (ModelState.IsValid)
			{
				IdentityUser? user = await userManager.FindByNameAsync(model.UserName);
				if (user != null)
				{
					await signInManager.SignOutAsync();
					Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, false);

					if (result.Succeeded)
						return Redirect(returnUrl ?? "/");
				}

                ModelState.AddModelError(nameof(LoginViewModel.UserName), "Неверный логин или пароль");
            }
            return Login(returnUrl);
		}

		[Authorize]
		public async Task<IActionResult> Logout()
		{
			await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Admin");
		}
	}
}

TestWebApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TestWebApplication.Domain;
using TestWebApplication.Models;

namespace TestWebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly DataManager dataManager;

        public HomeController(ILogger<HomeController> logger, DataManager data)
        {
            _logger = logger;
            dataManager = data;
        }

        public IActionResult Index()
        {
            return View(dataManager.TextFields.GetByCodeWord("PageIndex"));
        }

        public IActionResult Privacy()
        {
            return View(dataManager.TextFields.GetByCodeWord("PageContacts"));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestWebApplication/Areas/Admin/Views/Admin/Index.cshtml
@model IQueryable<ServiceItem>;
@{
    ViewBag.Title = "Панель администратора";
}

<div>
    <h1>@ViewBag.Title</h1>
    <div>
        <h3>Наши услуги</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="">Добавить услугу</a>
        </div>
        @if (Model.Any())
        {
            <div>
                @foreach (ServiceItem item in Model)
                {
                    <div>
                        <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="@item.Id">редактировать</a>
                        |
                        <form style="display:inline-block;" id="form-@item.Id" asp-area="Admin" asp-controller="ServiceItems" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@item.Id">
                            <a href="#" onclick="document.getElementById('form-@item.Id').onsubmit();">удалить</a>
                        </form>
                        |
                        <a asp-area="." asp-controller="Services" asp-action="Index" asp-route-id="@item.Id">
                            @($"{item.Title}")
                        </a>
                    </div>
                }
            </div>
        }
    </div>
    <div class="div-box">
        <h3>Редактировать страницу сайта</h3>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageServices">Наши услуги</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
    </div>
    <div class="div-box">
        <form asp-area="." asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" value="Выйти" />
        </form>
    </div>
</div>

TestWebApplication/Areas/Admin/Views/ServiceItems/Edit.cshtml
@model ServiceItem;
@{
    ViewBag.Title = "Редактировать запись";
}

<script src="~/js/ckeditor5-build-classic/ckeditor.js"></script>

<div>
    <h2>@ViewBag.Title</h2>
    <div>
        <form asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Subtitle"></label>
                <input asp-for="Subtitle" />
                <span asp-validation-for="Subtitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-block" src="~/img/@Model.TitleImagePath" />
                </div>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>
<script>
    window.onload = function () {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x => x.Text)');
        newCKEdit.updateElement();
    }
</script>

TestWebApplication/Areas/Admin/Views/TextFields/Edit.cshtml
@model TextField;
@{
    ViewBag.Title = "Редактировать запись";
}

<script src="~/js/ckeditor5-build-classic/ckeditor.js"></script>

<div>
    <h2>@ViewBag.Title</h2>
    <div>
        <form asp-area="Admin" asp-controller="TextFields" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="CodeWord" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title"/>
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>
<script>
    window.onload = function(){
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x => x.Text)');
        newCKEdit.updateElement();
    }
</script>

TestWebApplication/Views/Home/Index.cshtml
@model TestWebApplication.Domain.Entities.TextField
@{
    ViewBag.Title = Model.Title;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div class="text-center" style="align-self:center">
    @Html.Raw(Model.Text);
</div>

TestWebApplication/Views/Shared/Css.cshtml
<link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
<noscript><link rel="stylesheet" href="~/css/noscript.css" /></noscript>

TestWebApplication/Views/Shared/FirstSection.cshtml
<section id="first" class="main special">
	<header class="major">
		<h2>Magna veroeros</h2>
	</header>
	<ul class="features">
		<li>
			<span class="icon solid major style1 fa-code"></span>
			<h3>Ipsum consequat</h3>
			<p>Sed lorem amet ipsum dolor et amet nullam consequat a feugiat consequat tempus veroeros sed consequat.</p>
		</li>
		<li>
			<span class="icon major style3 fa-copy"></span>
			<h3>Amed sed feugiat</h3>
			<p>Sed lorem amet ipsum dolor et amet nullam consequat a feugiat consequat tempus veroeros sed consequat.</p>
		</li>
		<li>
			<span class="icon major style5 fa-gem"></span>
			<h3>Dolor nullam</h3>
			<p>Sed lorem amet ipsum dolor et amet nullam consequat a feugiat consequat tempus veroeros sed consequat.</p>
		</li>
	</ul>
	<footer class="major">
		<ul class="actions special">
			<li><a href="generic.html" class="button">Learn More</a></li>
		</ul>
	</footer>
</section>

TestWebApplication/Views/Shared/Footer.cshtml
<footer id="footer">
	<section>
		<h2>Aliquam sed mauris</h2>
		<p>Sed lorem ipsum dolor sit amet et nullam consequat feugiat consequat magna adipiscing tempus etiam dolore veroeros. eget dapibus mauris. Cras aliquet, nisl ut viverra sollicitudin, ligula erat egestas velit, vitae tincidunt odio.</p>
		<ul class="actions">
			<li><a href="generic.html" class="button">Learn More</a></li>
		</ul>
	</section>
	<section>
		<h2>Etiam feugiat</h2>
		<dl class="alt">
			<dt>Address</dt>
			<dd>1234 Somewhere Road &bull; Nashville, TN 00000 &bull; USA</dd>
			<dt>Phone</dt>
			<dd>(000) 000-0000 x 0000</dd>
			<dt>Email</dt>
			<dd><a href="#">information@untitled.tld</a></dd>
		</dl>
		<ul class="icons">
			<li><a href="#" class="icon brands fa-twitter alt"><span class="label">Twitter</span></a></li>
			<li><a href="#" class="icon brands fa-facebook-f alt"><span class="label">Facebook</span></a></li>
			<li><a href="#" class="icon brands fa-instagram alt"><span class="label">Instagram</span></a></li>
			<li><a href="#" class="icon brands fa-github alt"><span class="label">GitHub</span></a></li>
			<li><a href="#" class="icon brands fa-dribbble alt"><span class="label">Dribbble</span></a></li>
		</ul>
	</section>
	<p class="copyright">&copy; Untitled. Design: <a href="https://html5up.net">HTML5 UP</a>.</p>
</footer>

TestWebApplication/Views/Shared/GetStarted.cshtml
<section id="cta" class="main special">
	<header class="major">
		<h2>Congue imperdiet</h2>
		<p>
			Donec imperdiet consequat consequat. Suspendisse feugiat congue<br />
			posuere. Nulla massa urna, fermentum eget quam aliquet.
		</p>
	</header>
	<footer class="major">
		<ul class="actions special">
			<li><a href="generic.html" class="button primary">Get Started</a></li>
			<li><a href="generic.html" class="button">Learn More</a></li>
		</ul>
	</footer>
</section>

TestWebApplication/Views/Shared/Header.cshtml
<header id="header" class="alt">
	<span class="logo"><img src="~/Img/logo.svg" alt="" /></span>
	<h1>Stellar</h1>
	<p>
		Just another free, fully responsive site template<br />
		built by <a href="https://twitter.com/ajlkn">ajlkn</a> for <a href="https://html5up.net">HTML5 UP</a>.
	</p>
</header>

TestWebApplication/Views/Shared/Introdution.cshtml
<section id="intro" class="main">
	<div class="spotlight">
		<div class="content">
			<header class="major">
				<h2>Ipsum sed adipiscing</h2>
			</header>
			<p>
				Sed lorem ipsum dolor sit amet nullam consequat feugiat consequat magna
				adipiscing magna etiam amet veroeros. Lorem ipsum dolor tempus sit cursus.
				Tempus nisl et nullam lorem ipsum dolor sit amet aliquam.
			</p>
			<ul class="actions">
				<li><a href="generic.html" class="button">Learn More</a></li>
			</ul>
		</div>
		<span class="image"><img src="~/Img/pic01.jpg" alt="" /></span>
	</div>
</section>

TestWebApplication/Views/Shared/MetaTag.cshtml
@if(@ViewBag.Title == null)
{
    <title>@ViewBag.Title</title>
}
else 
{
    <title>@TestWebApplication.Service.Config.ProjectName</title>
}
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
@if(ViewBag.Description != null)
{
    <meta name="description" content="ViewBag.Title" />
}

TestWebApplication/Views/Shared/Navigation.cshtml
<nav id="nav">
	<ul>
		<li><a href="#intro" class="active">Introduction</a></li>
		<li><a href="#first">First Section</a></li>
		<li><a href="#second">Second Section</a></li>
		<li><a href="#cta">Get Started</a></li>
	</ul>
</nav>

TestWebApplication/Views/Shared/Script.cshtml
<script src="~/js/jquery.min.js"></script>
<script src="~/js/jquery.scrollex.min.js"></script>
<script src="~/js/jquery.scrolly.min.js"></script>
<script src="~/js/browser.min.js"></script>
<script src="~/js/breakpoints.min.js"></script>
<script src="~/js/util.js"></script>
<script src="~/js/main.js"></script>

TestWebApplication/Views/Shared/SecondSection.cshtml
<section id="second" class="main special">
	<header class="major">
		<h2>Ipsum consequat</h2>
		<p>
			Donec imperdiet consequat consequat. Suspendisse feugiat congue<br />
			posuere. Nulla massa urna, fermentum eget quam aliquet.
		</p>
	</header>
	<ul class="statistics">
		<li class="style1">
			<span class="icon solid fa-code-branch"></span>
			<strong>5,120</strong> Etiam
		</li>
		<li class="style2">
			<span class="icon fa-folder-open"></span>
			<strong>8,192</strong> Magna
		</li>
		<li class="style3">
			<span class="icon solid fa-signal"></span>
			<strong>2,048</strong> Tempus
		</li>
		<li class="style4">
			<span class="icon solid fa-laptop"></span>
			<strong>4,096</strong> Aliquam
		</li>
		<li class="style5">
			<span class="icon fa-gem"></span>
			<strong>1,024</strong> Nullam
		</li>
	</ul>
	<p class="content">Nam elementum nisl et mi a commodo porttitor. Morbi sit amet nisl eu arcu faucibus hendrerit vel a risus. Nam a orci mi, elementum ac arcu sit amet, fermentum pellentesque et purus. Integer maximus varius lorem, sed convallis diam accumsan sed. Etiam porttitor placerat sapien, sed eleifend a enim pulvinar faucibus semper quis ut arcu. Ut non nisl a mollis est efficitur vestibulum. Integer eget purus nec nulla mattis et accumsan ut magna libero. Morbi auctor iaculis porttitor. Sed ut magna ac risus et hendrerit scelerisque. Praesent eleifend lacus in lectus aliquam porta. Cras eu ornare dui curabitur lacinia.</p>
	<footer class="major">
		<ul class="actions special">
			<li><a href="generic.html" class="button">Learn More</a></li>
		</ul>
	</footer>
</section>

TestWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<!--
	Stellar by HTML5 UP
	html5up.net | ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
	@await Html.PartialAsync("MetaTag")
	@await Html.PartialAsync("Css")
</head>
<body class="is-preload">

	<!-- Wrapper -->
	<div id="wrapper">

		<!-- Header -->
		@await Html.PartialAsync("Header")

		<!-- Nav -->
		@await Html.PartialAsync("Navigation")

		<!-- Main -->
		<div id="main">
			@RenderBody()
			<!-- Introduction -->
			@await Html.PartialAsync("Introdution")

			<!-- First Section -->
			@await Html.PartialAsync("FirstSection")

			<!-- Second Section -->
			@await Html.PartialAsync("SecondSection")

			<!-- Get Started -->
			@await Html.PartialAsync("GetStarted")

		</div>

		<!-- Footer -->
		@await Html.PartialAsync("Footer")

	</div>

	<!-- Scripts -->
	@await Html.PartialAsync("Script")

</body>
</html>